export default {
  lineWidth: '1px',
  lineType: 'solid',
  groupTitleLineHeight: '1.5714285714285714',
  margin: '16px',
  marginXS: '8px',
  menuActiveBarBorderWidth: '1px',
  menuActiveBarWidth: '0px',
  menuCollapsedIconSize: '16px',
  menuCollapsedWidth: '80px',
  menuIconMarginInlineEnd: '10px',
  menuItemWidth: 'calc(100% - 8px)',
  menuItemHeight: '40px',
  menuItemMarginInline: '4px',
  menuItemMarginBlock: '4px',
  motionDuration: '.3s',
  motionDurationMid: '.2s',
  padding: '16px',
};
